### ISSUE TITLE
container noto'g'ri ishlatilgan

### ISSUE THREAD

**Issue by AbdunazarovM** [Murodjon-Abdulazizov/Saralash#1]
https://github.com/Murodjon-Abdulazizov/Saralash/blob/4a2ad7cfaa8df405a0fb1bcc036f35ec51f39d5a/index.html#L18
![image](https://user-images.githubusercontent.com/79672855/133303320-3cb82eeb-cd3e-4696-b472-c050bc5eb8ec.png)
container har bir section, header va footerlar uchun alohida ishlatiladi sababi hopincha header footerlarni **background-color** lari oxirigacha davom etadi
![image](https://user-images.githubusercontent.com/79672855/133303965-24854de2-8ec4-4625-8fa6-70488a867007.png)

**Comment by Murodjon-Abdulazizov** [comment]
Aha tushunarli to'girladim va keyingi safar bunday hato qilmaslikka harakat qilaman

**Comment by Murodjon-Abdulazizov** [comment]
ok
