### ISSUE TITLE
paddingni noto'g'ri ishlatilishi

### ISSUE THREAD

**Issue by AbdunazarovM** [Murodjon-Abdulazizov/Saralash#2]
https://github.com/Murodjon-Abdulazizov/Saralash/blob/4a2ad7cfaa8df405a0fb1bcc036f35ec51f39d5a/css/styles.css#L56
![image](https://user-images.githubusercontent.com/79672855/133304401-38a2d889-9f49-4724-822a-07e2292a9a28.png)
bu yerda padding emas balki margin berish kerak yana `a`ga emas balki `li` larga berilishi kerak edi

**Comment by Murodjon-Abdulazizov** [comment]
to'g'irladim
