### ISSUE TITLE
logodagi hatilik

### ISSUE THREAD

**Issue by AbdunazarovM** [Murodjon-Abdulazizov/Saralash#3]
https://github.com/Murodjon-Abdulazizov/Saralash/blob/4a2ad7cfaa8df405a0fb1bcc036f35ec51f39d5a/index.html#L21
![image](https://user-images.githubusercontent.com/79672855/133305609-606227a7-7aff-465b-a16e-78d16d87cb7a.png)
**logo** da text bilan rasmni bitta qilib olish kerak rasm ko'rinishida

**Comment by Murodjon-Abdulazizov** [comment]
Menimcha maketda shunday edi videoda ham shunday qilingan faqat a ni ichida emas spam element ichida ekan
