### ISSUE TITLE
padding va margin umumiy

### ISSUE THREAD

**Issue by AbdunazarovM** [Murodjon-Abdulazizov/Saralash#8]
ko'p qaytarilganligi sabab bittalab yozilgani yo'q `<header>`,  `<main>` va `<footer>`da ham bu xatolarga ko'p yo'l qo'yilgan

**Comment by Murodjon-Abdulazizov** [comment]
Tushunarli

**Comment by Murodjon-Abdulazizov** [comment]
tushunarli
